#!/bin/bash
# Quick gh-pages cleanup without confirmations (use with caution!)

set -e

echo "🚀 Quick gh-pages cleanup starting..."

# Check current branch
if [ "$(git branch --show-current)" != "master" ]; then
  echo "❌ Must be on master branch"
  exit 1
fi

# Check for uncommitted changes
if [ -n "$(git status --porcelain)" ]; then
  echo "❌ Uncommitted changes detected. Commit or stash first."
  exit 1
fi

echo "📥 Fetching current gh-pages content..."
git branch -D gh-pages 2>/dev/null || true
git checkout --orphan gh-pages-new
git rm -rf . 2>/dev/null || true
git fetch --depth=1 origin gh-pages
git checkout FETCH_HEAD -- . 2>/dev/null || true

echo "💾 Creating clean commit..."
git add .
git commit --allow-empty -m "chore: rebuild gh-pages with clean history

- Removed 28GB of historical commits
- Preserved current report files
- Optimized for fast CI/CD checkout

🤖 Generated by cleanup script
"

echo "⬆️  Force pushing to origin..."
git push origin gh-pages-new:gh-pages --force

echo "🧹 Cleaning up..."
git checkout master
git branch -D gh-pages-new

echo "✅ Done! gh-pages branch rebuilt successfully."
echo "   GitHub Pages will update in 2-5 minutes."
